#!/usr/bin/env bash

{ # this ensures the entire script is downloaded

  # exit if anything fails
  set -e

  # setup some formatting vars
  TERM=${TERM:-"dumb"}
  green=$(tput setaf 10)
  yellow=$(tput setaf 11)
  white=$(tput setaf 15)
  gray=$(tput setaf 8)
  bold=$(tput bold)
  normal=$(tput sgr0)

  # retrieve the latest version number
  latestVersion="$(curl -s https://api.github.com/repos/simbo/rm-node_modules/releases/latest | grep "tag_name" | cut -d '"' -f 4)"

  # inform about installation
  printf "\nInstalling ${bold}rm-node_modules $latestVersion${normal} to ${bold}$HOME/bin${normal}...\n"

  # ask for confirmation
  printf "Press [ENTER] to continue.\n"
  IFS= read -s -n 1 key
  if [[ $key != "" ]]; then
    printf "\n${gray}Aborted.${normal}\n"
    exit 0

  # ensure ~/bin directory exists
  mkdir -p $HOME/bin

  # change to ~/bin directory
  cd $HOME/bin

  # remove existing version and symlink
  rm -f ./rm-node_modules
  rm -f ./rmnm

  # inform about downloading
  printf "\n${gray}Downloading...${normal}\n"

  # download latest version
  curl -s https://raw.githubusercontent.com/simbo/rm-node_modules/$latestVersion/rm-node_modules -o ./rm-node_modules

  # make script executable
  chmod +x ./rm-node_modules

  # inform about linking
  printf "${gray}Linking...${normal}\n"

  # create symlink
  ln -s ./rm-node_modules rmnm

  # ensure ~/bin is within PATH
  export PATH="$HOME/bin:$PATH"

  # inform about status
  printf "${gray}Done.${normal}\n"
  printf "\n${green}Successfully installed ${bold}rm-node_modules $latestVersion${normal}${green}.${normal}\n"

  # inform about PATH
  printf "\nIf $HOME/bin is not within your PATH by default, add this line to your shell profile:\n"
  printf "\n  ${white}${bold}export PATH=\"\$HOME/bin:\$PATH\"${normal}\n"

  # inform about execution
  printf "\nRun the script using ${yellow}${bold}rm-node_modules${normal} or ${yellow}${bold}rmnm${normal}.\n"

  # inform about usage
  printf "\nRun ${yellow}${bold}rmnm -h${normal} to display usage information.\n"

  # inform about configuration
  printf "\nYou may want to configure your default base directory using ${yellow}${bold}rmnm -c <DIR>${normal}.\n"

} # this ensures the entire script is downloaded