#!/usr/bin/env bash

{ # this ensures the entire script is downloaded #

  set -e
  TERM=${TERM:-"dumb"}
  green=$(tput setaf 10)
  yellow=$(tput setaf 11)
  white=$(tput setaf 15)
  bold=$(tput bold)
  normal=$(tput sgr0)
  binDir=$HOME/bin
  printf "\nInstalling rm-node_modules to $binDir...\n"
  mkdir -p $binDir
  target=$binDir/rm-node_modules
  rm -f $binDir/rm-node_modules
  printf "\nDownloading...\n\n"
  curl https://raw.githubusercontent.com/simbo/rm-node_modules/master/rm-node_modules -o $binDir/rm-node_modules
  chmod +x $binDir/rm-node_modules
  printf "\nLinking...\n"
  rm -f $binDir/rmnm
  cd $binDir
  ln -s ./rm-node_modules rmnm
  export PATH="$binDir:$PATH"
  printf "\nDone.\n"
  printf "\n${green}Successfully installed ${bold}rm-node_modules $(rmnm -v)${normal}${green}.${normal}\n"
  printf "\nIf $binDir is not within your PATH, add this line to your shell profile:\n"
  printf "  ${white}${bold}export PATH=\"\$HOME/bin:\$PATH\"${normal}\n"
  printf "\nRun the script using ${yellow}${bold}rm-node_modules${normal} or ${yellow}${bold}rmnm${normal}.\n"

} # this ensures the entire script is downloaded #